apiVersion: batch/v1
kind: Job
metadata:
  name: caf-pipeline
spec:
  template:
    spec:
      containers:
      - name: caf-pipeline
        image: caf-pipeline
        imagePullPolicy: Never
        args: ["--mode", "evaluate"]
      restartPolicy: Never
  backoffLimit: 0
